version: 0.2

phases:
  install:
    commands:
      - echo Instalando dependências...
      - npm install
  build:
    commands:
      - echo Construindo a aplicação...
      - npm run build
  post_build:
    commands:
      - echo Build concluído

artifacts:
  files:
    - '**/*'
  base-directory: build
