version: 1.0

phases:
  install:
    commands:
      - echo "Instalando dependências..."
      - chmod +x gradlew
      - ./gradlew build
  build:
    commands:
      - echo "Construindo a aplicação..."
      - ./gradlew assemble
  post_build:
    commands:
      - echo "Build concluído"
      - echo "Arquivos construídos:"
      - ls build/libs/

artifacts:
  files:
    - 'build/libs/*.jar'
