branch-defaults:
  main:
    environment: ES2TF-dev
    group_suffix: null
environment-defaults:
  ES2TF-dev:
    branch: main
    repository: ES2_TF
global:
  application_name: ES2_TF
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Corretto 17 running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
